### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by Kali123411** [kasplex/indexer-executor#1]
Set up per the directions with rockdb but it fails to run, is the Cassandra required?:
![image](https://github.com/user-attachments/assets/87206759-0f9f-48e9-bb15-daee88aa98ff)

**Comment by jeanku** [comment]
Cassandra database is necessary, and the current script is responsible for processing the raw data of Kaspa OP in Cassandra.

**Comment by Kali123411** [comment]
> Cassandra database is necessary, and the current script is responsible for processing the raw data of Kaspa OP in Cassandra.

thanks
